#!/bin/bash

echo "TEST 2: z=10, n=1000"
./bin/gen > test_in/input2 <<< "10 1000000000 1000"
echo "preparing data..."
./bin/D < test_in/input2 > test_out/out_good

files="D D2 D3 Dt Do"

for f in $files; do
    suffix=${f#D}
    time "bin/$f" < test_in/input2  > test_out/out$suffix
    res=$(diff test_out/out_good test_out/out$suffix)
    
    if [ -n "$res" ]; then
        echo "Difference found in D$suffix"
    else
        echo "Success for D$suffix"
    fi
done